export const users = [
  { id: 1, profilepicture: "assets/person/p1.webp", username: "Medini Rao" },
  { id: 2, profilepicture: "assets/person/p2.webp", username: "Jane Doe" },
  { id: 3, profilepicture: "assets/person/p3.webp", username: "Sharon" },
  { id: 4, profilepicture: "assets/person/p4.webp", username: "Nancy" },
  { id: 5, profilepicture: "assets/person/p5.webp", username: "David" },
  { id: 6, profilepicture: "assets/person/p6.webp", username: "Sam" },
];

export const posts = [
  {
    id: 1,
    desc: "Love of my Life",
    photo: "assets/posts/9.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "assets/posts/po3.png",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "assets/posts/po4.png",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "assets/posts/po5.png",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/posts/po6.png",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/posts/post1.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "assets/posts/post2.webp",
    date: "2 days ago",
    userId: 2,
    like: 52,
    comment: 3,
  },
];
